### PR TITLE
Subscribe to more than one multicast group for input

### PR DESCRIPTION
**Pull request by ifsnop**
Radar data distribution in our organisation is done using one multicast group for each surveillance sensor. To be able to listen to more than one sensor, this modification was needed. 

The same syntax is used with the "-i" modifier, but more than one group could be entered by using the "@" as separator between groups definitions. Documentation with the -h switch has been updated with an example.

Code changes were kept to a minimum, mainly modifing udpdevice code. There is only one inputchannel defined, but now it can manage more subscriptions. Verification code of -i parameter syntax was moved to udpdevice. Opinions are welcomed!

### CODE REVIEW

**Comment by dsalantic** [comment]
Hi, we also use different multicast groups for different radars, so I start multiple instances of asterix tool, one for each radar.
But, I agree that your solution should be more efficient. 
I will test it in my system and than I'll merge the changes to master branch.
Thank you again for your participation in this project and sharing your improvement.

**Comment by dsalantic** [comment]
It seems that there is a bug in your solution. After few seconds I get segmentation fault in this line of  udpdevice.cxx in : 
for(unsigned int i; i<_socketDesc.size() || _countToRead>0; i++)

I believe it should be: 
for(unsigned int i; i<_socketDesc.size() && _countToRead>0; i++)

When changed, I do not receive segmentation fault any more, but I receive many errors: "Packet too big!". So, it looks like there is still some problem with reading UDP multicast data.
Let me know if you find the cause.
Thanks

**Comment by ifsnop** [comment]
I will check, but I have spoted a mistake...  Variable i is not
initialized!

**Comment by ifsnop** [comment]
Now it should be fixed. Please, test in your side. Do you prefer this kind of patches submitted from another branch or is it ok if they come from master?
Regards,

**Pull request merged**
