### PR TITLE
Specs converter

### PR DESCRIPTION
**Pull request by zoranbosnjak**
The conversion from json to xml is very close to the original xml. Please note the following differences in the generated file:

- Item 000 has 1 nesting level in json, but 2 levels in xml. The second level must be generated, which results in name "000" being duplicated.

- In the original xml item 605 and item 610 looks like a mistake (Fixed, instead of Repetitive).

- BDS is not included in json. Only number of bits is defined. Is it possible to define BSD at some other level (different file)?

- I don't understand the meaning of "encode hex". If it's only for the display purposes, it might be better to omit this in json/xml and leave it up to the application to decide the output format.
Currently the following "content types" are supported in JSON:
  - raw (identifiers, SAC, SIC ... for values with no specific conversion, something like unsigned integer, but as a different data type)
  - table
  - string (ascii, icao, octal)
  - integer (signed, unsigned, for example hours, minutes, seconds)
  - quantity (signed, unsigned, scaling, unit...)

If the "hex" is the same as "raw", then it could be included in xml. Otherwise, there is currently no way to generate "hex" attribute.

- Rendering of some decimal numbers are unfortunate, like `0.10000000000000000555111512313`, instead of `0.1`. But this should not confuse the parser, since this is the same as python is concerned
```python
>>> 0.10000000000000000555111512313 == 0.1
True
```
* SP and RE items do not have further structure. They are currently defined as `Extended`. I am not sure if they need deeper definitions.

### CODE REVIEW

**Comment by zoranbosnjak** [comment]
One more inconsistency was found in the original xml FSPEC items 290 and 380.
(one is using 2x 1byte, another is using 1x 2bytes to describe the FSPEC)
Generated file is using the mechanism as used in item 290.

I am also not sure if <BitsValue> is needed in FSPEC listing as in item 390.

**Comment by dsalantic** [comment]
OK, great, we are getting closer now.
I merged it and made some modification to original XML and also some changes in converter. 
Please pull the changes and take a look and see my comments below:

> Item 000 has 1 nesting level in json, but 2 levels in xml. The second level must be generated, which results in name "000" being duplicated.

I don't understand this. Why can't you generate 2 levels in json as well like in 015 ?

> In the original xml item 605 and item 610 looks like a mistake (Fixed, instead of Repetitive). 

FIXED

> BDS is not included in json. Only number of bits is defined. Is it possible to define BSD at some other level (different file)?

BDS format is defined in asterix_bds.xml. When my parser finds <BDS/> it searches the format in asterix_bds.xml, so I need BDS indication in json. We need to find a way how to define it. 

> I don't understand the meaning of "encode hex". If it's only for the display purposes, it might be better to omit this in json/xml and leave it up to the application to decide the output format.

Hex is used mainly for presentation and could be replaced with unsigned and let the application decode it, except for the cases where length of item is larger then 8 bytes (then it will not fit to unsigned long).
Example of such case is CAT240, where video signal from radar is transfered in 64 or 256 octects.
So, I suppose that best way is to generate "hex" in all cases where you have "raw" format. 

Note that there is also "6bitschar" format. This is also for presentation, but maybe I could put it to raw and present it as hex.

> Rendering of some decimal numbers are unfortunate, like 0.10000000000000000555111512313, instead of 0.1. But this should not confuse the parser, since this is the same as python is concerned
>>> 0.10000000000000000555111512313 == 0.1
True

See in code how I fixed it.

> SP and RE items do not have further structure. They are currently defined as Extended. I am not sure if they need deeper definitions.

Unfortunately empty "Explicit" will confuse my parser, so we should add Fixed inside.


> One more inconsistency was found in the original xml FSPEC items 290 and 380.
(one is using 2x 1byte, another is using 1x 2bytes to describe the FSPEC)
Generated file is using the mechanism as used in item 290.

OK, I fixed it in original format.

> I am also not sure if is needed in FSPEC listing as in item 390.

I'm not sure what do you mean here, but maybe its fixed now.

**Comment by zoranbosnjak** [comment]
@dsalantic your updated xml and the generated xml looks indeed very similar. Your fixes on the script also look OK. Let me try to summarize and comment the remaining differences (ignoring the trivial differences in "desc" attribute):

**1. Item `000` (and `015`)**
Item `015` has the same problem as `000`, but I did not spot it before.

It all depends on how you want to use item names to reference bits in the structure. For example:

`010` (referes to 16 bits)
`010/SAC` (8 bits)
`010/SIC` (8 bits)

`000` (8 bits)
`000/MsgTyp`(the same as `000`, so it's redundant)

`015` (8 bits)
`015/SI` (the same as `015`)

The only problem really is the subitem **name** on the second level, which needs to be added (like `MsgTyp` and `SI` above). What I propose to do with items with no further structure is to keep the definitions (in the .ast and .json) as **element** (instead of group with the single item). I am already using this mechanism in other categories.
The second level in the xml can still be generated (as demonstrated in current `000`). It is only the question what to put in the `<BitsShortName>`:
* an empty string;
* the same as a parent name;
* something else...

If your xml parser can handle empty string, this could be a good indication for the generated second level.

**2. encode="6bitschar" in item "245"**
For the cases like this, there is a content type "string icao".
I will fix the .ast file and regenerate the file in my next commit.

**3. BDS indication**
I understand the situation now.
This can be fixed by introducing new "BDS" content type in the original .ast (and .json), so that xml can be generated exactly as expected. Unless you have any other idea, I will fix this in my next commit.

**4. Explicit type**
I understand you need *Fixed* inside *Explicit*. 
* Is this *Fixed* content in xml always the same 8 bits?
* Or there are other cases so the .ast syntax needs to be extended to support it? If yes, can you please give me several examples (different cases) of how RE and SP fields can look like.

Please comment and let me know if there are other issues with the conversion.

**Comment by dsalantic** [comment]
@zoranbosnjak 
**1. Item 000 (and 015)**
I understand your point, but my parser needs to have 000/MsgTyp (same as 015/SI).
So, I propose that you always use group even there is only one element in category. I think this will be more clear.

**2. encode="6bitschar" in item "245"**
OK, great

**3. BDS indication**
BDS content type sound good for me

**4. Explicit type**
Explicit type does not contain only Fixed type, but it can contain any available type inside (Fixed, Compound, Repetitive, Variable). You can see the example in CAT021 RE (EUROCONTROL-SPEC-0149-12-A). 
So, Explicit type (usually used in SP and RE items) is just a container for any other type, but since it is not always defined (e.g. SP is never defined in standard) I always by default put as Fixed(1) to be able to show content. If this is not acceptable I can modify my parser to support empty explicit and treat it as Fixed(1).

**DataItemFormat**
I propose that you add item format description of each item to ast file (e.g. "One-octet fixed length Data Item") because it is always defined in specification anyway. There is no any practical use of this, but maybe just a check that your format is correct. If you think it's not useful it's OK for me to automatically generate it or drop it from XML since I'm not using it anyway.

Everything else looks fine for me.

**Comment by zoranbosnjak** [comment]
@dsalantic 

I can not easily fix **1.** as you propose. It would break my existing apps. But the problem is even bigger - **short item names** in general. Cat011 is not a problem (you have defined it both .xml and .ast). But other existing categories have minor differences in short item names. The source of the problem is of course the original PDF, because not all short names are defined (some item names need to be invented).

To handle both problems, I propose the following layer of flexibility... In addition to the `json-to-xml.py` script, there could be additional file `config.py` that would be used by the script during conversion. It would contain something like this (configuration file in python syntax):

```python
# config.py
# imported as a separate file or
# included at the top of the conversion script itself

# top level item insertions
top_item_insert = {
    '011': {                # category
        '000': 'MsgTyp',    # top item name -> subitem name
        '015': 'SI',
        # more insert rules...
    },
    # more categories...
}

# item name mappings
item_renames = {
    '062': {                    # category
        ['105', 'LAT']: 'Lat',  # original name -> new name
        ['105', 'LON']: 'Lon',
        # more rename rules...
    }
    # more categories...
}
```
In case of any other incompatibility, the configuration file can be extended accordingly. 
At the moment, I don't see any other solution, without breaking one side or the other.
Before implementing, let me know if this works for you.

**2. and 3. will be fixed**

**4 (Explicit type)**
I will study the document and get back to this problem.

**DataItemFormat**
I will try to extend the generated description xml, at least for items with a-priory known size.

**Comment by dsalantic** [comment]
@zoranbosnjak 
OK, no problem. This converter was a good exercise to see that both formats are compatible.
I don't care if some (or many) short names change later, it's important that short name is unique and consists on one word.
My plan is anyway to once when most categories are defined (and if this is accepted as de-facto standard) adapt my parser to directly use your JSON files.

**Comment by ifsnop** [comment]
Hi Samir,

Are you planning to drop XML definitions in favour of JSON or to support
both of them? May I ask you why are you planning this change?

Damir Salantic:

> @zoranbosnjak <https://github.com/zoranbosnjak>
> OK, no problem. This converter was a good exercise to see that both
> formats are compatible.
> I don't care if some (or many) short names change later, it's important
> that short name is unique and consists on one word.
> My plan is anyway to once when most categories are defined (and if this is
> accepted as de-facto standard) adapt my parser to directly use your JSON
> files.
>

**Comment by dsalantic** [comment]
No, I don't plan to drop XML definitions, but only to extend the functionality of Asterix parser in a way to support different definitions (either in JSON or in XML).
Zoran is working on interesting project to enable easy definition of Asterix categories and tool to convert those definitions to different formats. In case that this project succeeds I'd like to be ready to support it in Asterix parser.

Anyway, there is a task in progress in Eurocontrol to define and publish Asterix category definitions in machine readable format (and both Zoran and me are in contact with Eurocontrol regarding that), so for sure we will go in that direction eventually when that happens.

**Pull request merged**
