### PR TITLE
Add support for .gps files

### PR DESCRIPTION
**Pull request by ifsnop**
Add support for .gps files, which timestamp each datablock.

### CODE REVIEW

**Comment by ifsnop** [comment]
Failure in travis has nothing to do with the contents of the PR. Please consider merging, I have tried my best to follow coding rules and implemented classes. It is very useful for me to merge it, so I don't need to rebase each time.

**Comment by dsalantic** [comment]
Thanks for your contribution. 
I can't test it because I don't have any sample file, but I confirm that it will not interfere with other formats, so I merged it to master branch.

**Comment by ifsnop** [comment]
I could provide a sample file, to enable testing.

I want to send you a modification to use timestamp from gps files into the timestamp field. Would you mind if I also change timestamp to float, so it can hold the full gettimeofday information (seconds with millisecond accuracy since 1970) ? It is a major change, and I don't know if I could break other applications using this program.

**Comment by dsalantic** [comment]
It would be nice if you could send me a sample file, so I can include it in automated tests.
Note that timestamp is already in milliseconds since 1970, so there is not need to change it to float, unless you need sub milliseconds accuracy. Is that what you need ?
I just noticed that you added m_nTimeStamp to CAsterixFormatDescriptor, but I don't see that it is used anywhere. Time is set directly through Descriptor.m_InputParser.parsePacket and it should be in milliseconds since 1970.

**Comment by ifsnop** [comment]
But timestamp is not since 1970, but from 00:00:00 of current day:
~~~
unsigned long nTimestamp = (tp.tv_sec % 86400) * 1000 + tp.tv_usec / 1000;
~~~

Regarding m_nTimeStamp, it was left during some testing. I will send a PR removing it, with a GPS file and some testing, and code to use time from GPS file.

**Pull request merged**
